# reset
set_property PACKAGE_PIN U18 [get_ports reset]
	set_property IOSTANDARD LVCMOS33 [get_ports reset]
	
# clock
set_property PACKAGE_PIN W5 [get_ports {clk_fpga}]
	set_property IOSTANDARD LVCMOS33 [get_ports {clk_fpga}]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports {clk_fpga}]

# USB-RS32
set_property PACKAGE_PIN B18 [get_ports mcs_rx]
	set_property IOSTANDARD LVCMOS33 [get_ports mcs_rx]
set_property PACKAGE_PIN A18 [get_ports mcs_tx]
	set_property IOSTANDARD LVCMOS33 [get_ports mcs_tx]
	
# LED
set_property PACKAGE_PIN L1 [get_ports led[15]]
	set_property IOSTANDARD LVCMOS33 [get_ports led[15]]
set_property PACKAGE_PIN P1 [get_ports led[14]]
	set_property IOSTANDARD LVCMOS33 [get_ports led[14]]
set_property PACKAGE_PIN N3 [get_ports led[13]]
	set_property IOSTANDARD LVCMOS33 [get_ports led[13]]
set_property PACKAGE_PIN P3 [get_ports led[12]]
	set_property IOSTANDARD LVCMOS33 [get_ports led[12]]
set_property PACKAGE_PIN U3 [get_ports led[11]]
	set_property IOSTANDARD LVCMOS33 [get_ports led[11]]
set_property PACKAGE_PIN W3 [get_ports led[10]]
	set_property IOSTANDARD LVCMOS33 [get_ports led[10]]
set_property PACKAGE_PIN V3 [get_ports led[9]]
	set_property IOSTANDARD LVCMOS33 [get_ports led[9]]
set_property PACKAGE_PIN V13 [get_ports led[8]]
	set_property IOSTANDARD LVCMOS33 [get_ports led[8]]
set_property PACKAGE_PIN V14 [get_ports led[7]]
	set_property IOSTANDARD LVCMOS33 [get_ports led[7]]
set_property PACKAGE_PIN U14 [get_ports led[6]]
	set_property IOSTANDARD LVCMOS33 [get_ports led[6]]
set_property PACKAGE_PIN U15 [get_ports led[5]]
	set_property IOSTANDARD LVCMOS33 [get_ports led[5]]
set_property PACKAGE_PIN W18 [get_ports led[4]]
	set_property IOSTANDARD LVCMOS33 [get_ports led[4]]
set_property PACKAGE_PIN V19 [get_ports led[3]]
	set_property IOSTANDARD LVCMOS33 [get_ports led[3]]
set_property PACKAGE_PIN U19 [get_ports led[2]]
	set_property IOSTANDARD LVCMOS33 [get_ports led[2]]
set_property PACKAGE_PIN E19 [get_ports led[1]]
	set_property IOSTANDARD LVCMOS33 [get_ports led[1]]
set_property PACKAGE_PIN U16 [get_ports led[0]]
	set_property IOSTANDARD LVCMOS33 [get_ports led[0]]
	
# buttons
set_property PACKAGE_PIN T18 [get_ports {sw_up}]
	 set_property IOSTANDARD LVCMOS33 [get_ports {sw_up}]
set_property PACKAGE_PIN U17 [get_ports {sw_down}]
	 set_property IOSTANDARD LVCMOS33 [get_ports {sw_down}]
set_property PACKAGE_PIN W19 [get_ports {sw_left}]
	 set_property IOSTANDARD LVCMOS33 [get_ports {sw_left}]
set_property PACKAGE_PIN T17 [get_ports {sw_right}]
	 set_property IOSTANDARD LVCMOS33 [get_ports {sw_right}]
	
# Seven segment
# seven segment display
set_property PACKAGE_PIN W7 [get_ports {sv_disp[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {sv_disp[0]}]
set_property PACKAGE_PIN W6 [get_ports {sv_disp[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {sv_disp[1]}]
set_property PACKAGE_PIN U8 [get_ports {sv_disp[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {sv_disp[2]}]
set_property PACKAGE_PIN V8 [get_ports {sv_disp[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {sv_disp[3]}]
set_property PACKAGE_PIN U5 [get_ports {sv_disp[4]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {sv_disp[4]}]
set_property PACKAGE_PIN V5 [get_ports {sv_disp[5]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {sv_disp[5]}]
set_property PACKAGE_PIN U7 [get_ports {sv_disp[6]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {sv_disp[6]}]
# seven segment connector
set_property PACKAGE_PIN U2 [get_ports {sv_anode[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {sv_anode[0]}]
set_property PACKAGE_PIN U4 [get_ports {sv_anode[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {sv_anode[1]}]
set_property PACKAGE_PIN V4 [get_ports {sv_anode[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {sv_anode[2]}]
set_property PACKAGE_PIN W4 [get_ports {sv_anode[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {sv_anode[3]}]
	
	
# added
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
